import { useState } from 'react';
import { ActivityIndicator, Linking, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { Feather } from '@expo/vector-icons';
import { Image } from 'expo-image';
import { useGetCurrentUser } from '@workspace/api-client-react';
import { EmptyState } from '@/components/empty-state';
import { useColors } from '@/hooks/useColors';
import { apiUrl } from '@/lib/api-url';
import { CosmicBackground } from '@/components/cosmic-background';

export default function ProfileScreen() {
  const colors = useColors();
  const user = useGetCurrentUser();
  const [expanded, setExpanded] = useState(false);
  if (user.isLoading) return <View style={[styles.center, { backgroundColor: colors.background }]}><CosmicBackground /><ActivityIndicator color={colors.primary} /></View>;
  if (user.isError || !user.data) return <View style={[styles.screen, { backgroundColor: colors.background }]}><CosmicBackground /><EmptyState icon="user" title="Profile" message="Sign in to see your profile, saved Blasts, and settings." actionLabel="Sign In" onAction={() => { void Linking.openURL(`https://${process.env.EXPO_PUBLIC_DOMAIN ?? ''}/sign-in`); }} /></View>;
  const profile = user.data;
  return <ScrollView style={[styles.screen, { backgroundColor: colors.background }]} contentContainerStyle={styles.content}><CosmicBackground /><View style={[styles.cover, { backgroundColor: colors.secondary }]}><View style={[styles.coverGlow, { backgroundColor: colors.primary }]} /></View><View style={styles.profileTop}>{profile.avatarUrl ? <Image source={{ uri: apiUrl(profile.avatarUrl) }} style={[styles.avatar, { borderColor: colors.background }]} contentFit="cover" /> : <View style={[styles.avatar, styles.avatarFallback, { backgroundColor: colors.accent, borderColor: colors.background }]}><Feather name="user" size={27} color={colors.primary} /></View>}<Pressable onPress={() => setExpanded(!expanded)} style={[styles.edit, { borderColor: colors.border }]}><Feather name="settings" size={16} color={colors.foreground} /><Text style={[styles.editText, { color: colors.foreground }]}>Settings</Text></Pressable></View><Text style={[styles.name, { color: colors.foreground }]}>{profile.displayName}</Text><Text style={[styles.handle, { color: colors.mutedForeground }]}>@{profile.username}</Text><Text style={[styles.bio, { color: colors.foreground }]}>{profile.bio || 'Making noise about what matters.'}</Text><View style={[styles.stats, { borderColor: colors.border }]}><Stat value={profile.blastCount} label="Blasts" colors={colors} /><Stat value={profile.followers} label="Followers" colors={colors} /><Stat value={profile.following} label="Following" colors={colors} /></View>{expanded ? <View style={[styles.settings, { backgroundColor: colors.card, borderColor: colors.border }]}><Text style={[styles.settingsTitle, { color: colors.foreground }]}>Settings</Text><Text style={[styles.settingText, { color: colors.mutedForeground }]}>Profile edits and preferences sync with the same BLASTERR account used on web.</Text><Pressable onPress={() => { void Linking.openURL(`https://${process.env.EXPO_PUBLIC_DOMAIN ?? ''}/settings`); }} style={styles.settingRow}><Feather name="external-link" size={16} color={colors.primary} /><Text style={[styles.settingLink, { color: colors.primary }]}>Manage on web</Text></Pressable></View> : null}<Text style={[styles.section, { color: colors.foreground }]}>Blasts</Text><EmptyState icon="activity" title="No blasts yet." /></ScrollView>;
}
function Stat({ value, label, colors }: { value: number; label: string; colors: ReturnType<typeof useColors> }) { return <View style={styles.stat}><Text style={[styles.statValue, { color: colors.foreground }]}>{value}</Text><Text style={[styles.statLabel, { color: colors.mutedForeground }]}>{label}</Text></View>; }
const styles = StyleSheet.create({ screen: { flex: 1 }, content: { paddingBottom: 40 }, center: { flex: 1, alignItems: 'center', justifyContent: 'center' }, cover: { height: 150, overflow: 'hidden' }, coverGlow: { width: 220, height: 220, borderRadius: 110, opacity: 0.15, position: 'absolute', right: -40, top: -80 }, profileTop: { paddingHorizontal: 20, marginTop: -35, flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-end' }, avatar: { width: 76, height: 76, borderRadius: 38, borderWidth: 4 }, avatarFallback: { alignItems: 'center', justifyContent: 'center' }, edit: { flexDirection: 'row', gap: 7, alignItems: 'center', paddingHorizontal: 12, paddingVertical: 8, borderRadius: 99, borderWidth: 1 }, editText: { fontFamily: 'Inter_600SemiBold', fontSize: 12 }, name: { fontFamily: 'Inter_700Bold', fontSize: 24, paddingHorizontal: 20, marginTop: 14 }, handle: { fontFamily: 'Inter_400Regular', fontSize: 13, paddingHorizontal: 20, marginTop: 3 }, bio: { fontFamily: 'Inter_400Regular', fontSize: 14, lineHeight: 21, paddingHorizontal: 20, marginTop: 14 }, stats: { flexDirection: 'row', marginTop: 20, marginHorizontal: 20, paddingVertical: 15, borderTopWidth: StyleSheet.hairlineWidth, borderBottomWidth: StyleSheet.hairlineWidth }, stat: { flex: 1, alignItems: 'center' }, statValue: { fontFamily: 'Inter_700Bold', fontSize: 18 }, statLabel: { fontFamily: 'Inter_400Regular', fontSize: 11, marginTop: 3 }, settings: { margin: 20, padding: 16, borderRadius: 16, borderWidth: 1 }, settingsTitle: { fontFamily: 'Inter_700Bold', fontSize: 15 }, settingText: { fontFamily: 'Inter_400Regular', fontSize: 13, lineHeight: 19, marginTop: 8 }, settingRow: { flexDirection: 'row', gap: 8, alignItems: 'center', marginTop: 15 }, settingLink: { fontFamily: 'Inter_700Bold', fontSize: 13 }, section: { fontFamily: 'Inter_700Bold', fontSize: 16, marginTop: 22, marginHorizontal: 20 } });